[package]
name = "seekable-zstd-py"
version = "0.1.1"
edition = "2021"
rust-version = "1.88"

[lib]
name = "seekable_zstd"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
seekable-zstd-core = { path = "../seekable-zstd-core" }
